// Scale: 200k rows x 30 columns. Times first render (posting `load` to the
// table becoming visible), each interaction (sort/filter/page/separator),
// and the JS heap via the CDP Performance domain. Prints a timing table to
// the test output.
//
// Targets (post-worker-migration — see docs/spec.md): first render under
// 2000ms, adding/changing a filter rule under 500ms, sorting under 500ms.
// Parsing/filtering/sorting now run in a Web Worker instead of blocking the
// main thread, which is what makes these tighter bounds meaningful instead
// of just generous slop. Pagination and separator changes don't have a
// dedicated target in the spec, so they keep a generous sanity bound (a
// true hang/crash still fails the suite). Doubled under CI for headroom on
// a slower/shared machine.
import { expect, test, type Page } from "@playwright/test";
import { bootShell, defaultViewState } from "../harness";
import { trackConsoleErrors } from "./stressHelpers";
import type { ViewState } from "../../../core/types";

const ROWS = 200_000;
const COLS = 30;
const CI_SLACK = process.env.CI ? 2 : 1;
const FIRST_RENDER_BOUND_MS = 2_000 * CI_SLACK;
const FILTER_BOUND_MS = 500 * CI_SLACK;
const SORT_BOUND_MS = 500 * CI_SLACK;
const GENEROUS_BOUND_MS = 30_000 * CI_SLACK;

/**
 * Posts a `load` message for a large generated fixture WITHOUT shipping
 * the (tens-of-MB) text through Playwright's Node -> browser argument
 * serialization — only the small `rowCount`/`colCount`/etc. cross that
 * boundary; the text itself is generated by an equivalent-shape generator
 * running inside the page. This matters for what "first render" actually
 * measures here: the real extension host constructs the `load` message
 * and posts it entirely within the (much faster) VS Code webview IPC
 * bridge, never through Playwright's CDP evaluate-argument path — routing
 * a 57 MB string through the latter costs ~2s of pure serialization
 * overhead by itself (measured directly), which would otherwise dominate
 * this test and measure Playwright's plumbing instead of the webview's
 * own load -> render pipeline.
 */
async function pushGeneratedLoad(
  page: Page,
  opts: { fileKey: string; rowCount: number; colCount: number; state: ViewState; defaultTableColumns: number },
): Promise<void> {
  await page.evaluate((o) => {
    function wideFixtureText(rowCount: number, colCount: number, delimiter = ","): string {
      const headers: string[] = [];
      for (let i = 0; i < colCount; i++) headers.push(`col_${i + 1}`);
      const lines: string[] = [headers.join(delimiter)];
      for (let r = 0; r < rowCount; r++) {
        const cells: string[] = [];
        for (let c = 0; c < colCount; c++) cells.push(c === 0 ? String(r) : `v${r}_${c}`);
        lines.push(cells.join(delimiter));
      }
      return lines.join("\n");
    }
    const text = wideFixtureText(o.rowCount, o.colCount);
    window.postMessage(
      { type: "load", fileKey: o.fileKey, text, state: o.state, defaultTableColumns: o.defaultTableColumns, defaultDelimiter: "" },
      "*",
    );
  }, opts);
}

test("200k rows x 30 columns: timing table for first render and each interaction, plus JS heap", async ({ page }) => {
  test.setTimeout(120_000);
  const consoleErrors = trackConsoleErrors(page);
  const timings: Array<{ step: string; ms: number }> = [];

  await bootShell(page);
  const client = await page.context().newCDPSession(page);
  await client.send("Performance.enable");

  async function heapMB(): Promise<number> {
    const { metrics } = await client.send("Performance.getMetrics");
    const m = metrics.find((x) => x.name === "JSHeapUsedSize");
    return m ? m.value / (1024 * 1024) : -1;
  }

  const t0 = Date.now();
  await pushGeneratedLoad(page, {
    fileKey: "file:///scale.csv",
    rowCount: ROWS,
    colCount: COLS,
    state: defaultViewState(),
    defaultTableColumns: 8,
  });
  await expect(page.locator("tr.data-row").first()).toBeVisible();
  const firstRenderMs = Date.now() - t0;
  timings.push({ step: "first render (load -> table visible)", ms: firstRenderMs });
  expect(firstRenderMs).toBeLessThan(FIRST_RENDER_BOUND_MS);

  const heapAfterLoad = await heapMB();

  async function timeStep(step: string, bound: number, action: () => Promise<void>): Promise<void> {
    const start = Date.now();
    await action();
    const ms = Date.now() - start;
    timings.push({ step, ms });
    expect(ms).toBeLessThan(bound);
  }

  await timeStep("sort by col_2 (header click, asc)", SORT_BOUND_MS, async () => {
    await page.locator("th", { hasText: "col_2" }).click();
    await expect(page.locator("th", { hasText: "col_2" }).locator(".sort-indicator")).toHaveText("▲");
  });

  await timeStep("filter: add rule, col_3 contains 'v1'", FILTER_BOUND_MS, async () => {
    await page.locator("#filters-btn").click();
    await page.locator("#add-rule-btn").click();
    const rule = page.locator(".rule-row").first();
    await rule.locator("select").nth(0).selectOption("col_3");
    await rule.locator("select").nth(1).selectOption("contains");
    await rule.locator('input[type="text"]').fill("v1");
    await expect(page.locator("#status-bar")).not.toHaveText(`Showing ${ROWS} of ${ROWS} rows`);
  });

  await timeStep("pagination: Next page", GENEROUS_BOUND_MS, async () => {
    await page.locator("#pager-next-btn").click();
    await expect(page.locator("#pager-page-input")).toHaveValue("2");
  });

  await timeStep("separator: switch to Semicolon (collapses to 1 column)", GENEROUS_BOUND_MS, async () => {
    await page.locator("#separator-select").selectOption(";");
    await expect(page.locator("th.sortable")).toHaveCount(1);
  });

  const heapAfterInteractions = await heapMB();
  timings.push({ step: "JS heap after first render (MB)", ms: Math.round(heapAfterLoad) });
  timings.push({ step: "JS heap after all interactions (MB)", ms: Math.round(heapAfterInteractions) });

  // eslint-disable-next-line no-console
  console.log("\n[stress] 200k x 30 timing table:");
  // eslint-disable-next-line no-console
  console.log(
    timings.map((t) => `  ${t.step.padEnd(55)} ${String(t.ms).padStart(8)}`).join("\n"),
  );

  expect(consoleErrors).toEqual([]);
});
